extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 20
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: opentelemetry-collector
          scrape_interval: 30s
          static_configs:
            - targets:
                - 0.0.0.0:8888

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25

  resource/metadata:
    attributes:
      - action: upsert
        key: cx.otel_integration.name
        value: coralogix-integration-ecs-ec2-app-otlp-debug

  batch:
    send_batch_max_size: 2048
    send_batch_size: 1024
    timeout: 1s

exporters:
  debug:
    verbosity: detailed

  coralogix:
    domain: coralogix.us
    private_key: ${env:CORALOGIX_PRIVATE_KEY}

    logs:
      headers:
        X-Coralogix-Distribution: ecs-ec2-app-otlp-debug/0.0.1

    metrics:
      headers:
        X-Coralogix-Distribution: ecs-ec2-app-otlp-debug/0.0.1

    traces:
      headers:
        X-Coralogix-Distribution: ecs-ec2-app-otlp-debug/0.0.1

    application_name: otel
    application_name_attributes:
      - cx.application.name
      - service.namespace
      - aws.ecs.cluster.name
      - aws.ecs.task.definition.family

    subsystem_name: integration
    subsystem_name_attributes:
      - cx.subsystem.name
      - service.name
      - aws.ecs.container.name

    timeout: 30s

service:
  extensions:
    - health_check
    - zpages
    - pprof

  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource/metadata
        - batch
      exporters:
        - debug
        - coralogix

    metrics:
      receivers:
        - otlp
        - prometheus
      processors:
        - memory_limiter
        - resource/metadata
        - batch
      exporters:
        - debug
        - coralogix

    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource/metadata
        - batch
      exporters:
        - debug
        - coralogix

  telemetry:
    logs:
      level: debug
      encoding: json

    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

    resource:
      cx.agent.type: gateway
      service.name: opentelemetry-collector
